use_frameworks!

platform :ios, '10.0'

target 'MFFileDownloader_Example' do
  pod 'MFFileDownloader', :path => '../'

  target 'MFFileDownloader_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
